# Generated by Django 3.2.5 on 2022-01-03 17:08

from django.conf import settings
from django.db import migrations, models
import gDoorControl.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gDoorControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorToggleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle_date', models.DateTimeField(verbose_name='date published')),
                ('pre_toggle_door_state', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=models.SET(gDoorControl.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
